### PR TITLE
New Feature: Quest Progress & Warfront

### PR DESCRIPTION
**Pull request by LiangYuxuan**
#### Quest Progress
* Tracks the progress of quests or questlines
* Allows giving custom function to handle and show
* Keep progress of some quests on weekly reset

#### Warfront
* Tracks the quests of completing scenario and killing world boss
* Resets when different faction captured the warfront, instand of on weekly reset

### Bug Fix
* Fixed `BonusFrame` ignores the config

### CODE REVIEW

**Comment by Stanzilla** [comment]
Awesome new feature! I am not quite sure of the naming of things. Should it be something like "Weakly Caps Progress"?

**Comment by LiangYuxuan** [comment]
_Quest Progress_ is not only designed for weekly quest. Daily quests are suiting it by changing `weekly = true` to `daily = true` in `trackedQuest`. Even some quest requiring weeks to do it, we can track it. So I think _Quest Progress_ is a proper name of it.

For the variables like `ProgressX`, X is the index of the data in `trackedQuest`. When showing in config, it is in localed string which is defined in `name`. Same as `WarfrontX` (use `GetName`). I use `ProgressX` and `WarfrontX` just like Currency and Emissary (`Currency1234` or `Emissary7`).

I think maybe variables in _Progress_ worth descriptive names as we cannot find out what it means by the name `Progress1`, but `Warfront1` definitely means the first warfront _Arathi Highlands_ and does not lead confuse. Also, the first tracked quest is fixed in SI, we can name it `ProgressConquest` but it maybe lead problem in ordering.

Actually, variables like `Progress1` are only in the default config table of SI, I think a proper comment can solve the problem. Like
```lua
    Progress1 = true, -- PvP Conquest
    Progress2 = true, -- Island Weekly
```
is really like the one of Emissary
```lua
    Emissary6 = false, -- LEG Emissary
    Emissary7 = true, -- BfA Emissary
```

**Comment by Stanzilla** [comment]
Yeah, I guess comments are fine for now

**Comment by Stanzilla** [comment]
image

hrm, the headers need a different color than the entries though, or an indent + icon like the currency section

**Comment by LiangYuxuan** [comment]
image

Maybe like this?

**Comment by Stanzilla** [comment]
That's good enough for now, thank you!

**Pull request merged**
