### PR TITLE
Reworked Emissary Module

### PR DESCRIPTION
**Pull request by LiangYuxuan**
* Mainly from #175 but not combined lines 
* Stored shared information like `questID` and `questNeed` in `db.Emissary`, and toon related in `db.Toon[toonName].Emissary`.
* Able to predict other toon's emissary quests.

### CODE REVIEW

**Comment by Stanzilla** [comment]
Do give me a ping when you are done with this PR, looks like you are still iterating?

**Comment by LiangYuxuan** [comment]
Just used for days to test and it works well now, so I'm ready now.

**Comment by LiangYuxuan** [comment]
In addition, new locate strings are added in dc73322, and might need to be imported to WoWAce.

**Comment by Stanzilla** [comment]
@LiangYuxuan just had this while testing on a lvl 110 char

```
3x SavedInstances\SavedInstances-@project-version@.lua:3900: attempt to concatenate local 'name' (a nil value)
SavedInstances\SavedInstances-@project-version@.lua:3900: in function `ShowTooltip'
SavedInstances\SavedInstances-@project-version@.lua:2421: in function `OnEnter'
Bazooka\Bazooka-v2.8.10.lua:1582: in function `showTip'
Bazooka\Bazooka-v2.8.10.lua:1387: in function <Bazooka\Bazooka.lua:1378>
```

**Pull request merged**
