### PR TITLE
rudimentary support for world quest weekly (#501)

### PR DESCRIPTION
**Pull request by prg**
basic support for #501

### CODE REVIEW

**Review by LiangYuxuan — CHANGES_REQUESTED** [review]
Add `relatedQuest = {62631},` to prevent it from displaying in Weekly Quest.

**Comment by LiangYuxuan** [comment]
Good one. Actually I love this since I'm working on this quest on 4 alts and loves to display progress. But I want to keep Progress Module small and not sure about if it's necessary to track the progress instand of completion.

**Comment by prg** [comment]
I like to track progress, because occasionally (all the time) I forget to pick it up on some characters.

**Review by LiangYuxuan — APPROVED** [review]

**Review by Stanzilla — APPROVED** [review]

**Comment by Stanzilla** [comment]
Nice, thank you!

**Pull request merged**
