### PR TITLE
[BfA] Updating some function names

### PR DESCRIPTION
**Pull request by Roddd**

### CODE REVIEW

**Comment by Roddd** [comment]
Original PR name was just the first change. I didn't plan on doing more changes. It's just whatever I was seeing on the error pop up plus whatever I could confirm was definite changes. Man, the lack of documentation for what's changed... ;__; Both are indeed trivial changes. I wasn't sure of any proper etiquette for commit messages so I used what I normally use -- exactly what I changed or what documentation I could find. :D

Good idea about branching. Again, I wasn't sure what kind of protocol is used for this repo. My apologies! D:

**Comment by Roddd** [comment]
I should note that I did test these on my account and the errors went away.

**Comment by SacredDuckwhale** [comment]
Don't worry, there isn't really any protocol. That's why the code is such a mess! :D

I'm just trying to keep it from getting worse. I'll test the changes as soon as I can.

**Comment by Stanzilla** [comment]
Thanks!

**Pull request merged**
