### PR TITLE
Added Treatises & Profession Quests

### PR DESCRIPTION
**Pull request by StevesExperiments**

### CODE REVIEW

**Review by LiangYuxuan — CHANGES_REQUESTED** [review]
Thanks a lot for finding and providing LOTS of quest ids!

But here are some little change wanted for reducing localization works by providing item ids by `.lid` to show hidden quest name in item name.

**Comment by StevesExperiments** [comment]
> Thanks a lot for finding and providing LOTS of quest ids!
> 
> But here are some little change wanted for reducing localization works by providing item ids by `.lid` to show hidden quest name in item name.

Are those the IDs like this?

https://www.wowhead.com/**item=194697**/draconic-treatise-on-alchemy

Otherwise, I don't know how to look up item IDs.

**Comment by LiangYuxuan** [comment]
> > Thanks a lot for finding and providing LOTS of quest ids!
> > But here are some little change wanted for reducing localization works by providing item ids by `.lid` to show hidden quest name in item name.
> 
> Are those the IDs like this? For ex:
> 
> https://www.wowhead.com/item=194697/draconic-treatise-on-alchemy
> 
> **item=194697**/draconic-treatise-on-alchemy
> 
> Otherwise, I don't know how to look up item IDs.

Yes, this is the item id and item name "Draconic Treatise on Alchemy" will be used.

**Review by LiangYuxuan — APPROVED** [review]

**Comment by LiangYuxuan** [comment]
Updated to use item name on knowledge item that can only be used once per week. For the quest that rewards knowledge, use the quest name. For Dragon Shard of Knowledge that drops from Disturbed Dirt or Expedition Scout's Pack, use build-in profession names.

**Review by Stanzilla — APPROVED** [review]

**Comment by Stanzilla** [comment]
Thank you!

**Pull request merged**
