### PR TITLE
Quick update for Patch 8.1

### PR DESCRIPTION
**Pull request by LiangYuxuan**

### CODE REVIEW

**Comment by Stanzilla** [comment]
Hey there! Thanks for your contribution! You have a few conflicts there, if you clear them up, I'll merge it!

**Comment by LiangYuxuan** [comment]
> Hey there! Thanks for your contribution! You have a few conflicts there, if you clear them up, I'll merge it!

Cleared conflicts in 75ea0d6, and shows no conflicts on github's PR page.

**Comment by Stanzilla** [comment]
image

**Comment by LiangYuxuan** [comment]
Shows different for me for some reason :p 

Anyway, I made a new PR, please check it

**Pull request closed without merging**
