### PR TITLE
travis-ci: add initial integration

### PR DESCRIPTION
**Pull request by jokeyrhyme**
basically does nothing, but hopefully a start on getting some automated quality checks in future

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Once this is merged, someone with project powers should go and enable Travis CI for this repository

**Comment by Stanzilla** [comment]
Ah, most of that we actually don't need, you can just copy our setup from WeakAuras https://github.com/WeakAuras/WeakAuras2/blob/master/.travis.yml minus the custom packager stuff but we might add that in the future as well

**Comment by jokeyrhyme** [comment]
Status: do not merge, WIP

**Comment by jokeyrhyme** [comment]
Status: okay, green, yay
I struggled for entirely too long to get a `sudo: false` build to work, which is a silly hill to die on :)

**Comment by Stanzilla** [comment]
What exactly do we need the makefile for?

**Comment by jokeyrhyme** [comment]
https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

Hmmm, I should drop the `sudo: false` everywhere then

**Comment by jokeyrhyme** [comment]
```
git:
  depth: 150
```

https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth
> Travis CI clones repositories to a depth of 50 commits, which is only really useful if you are performing git operations.

Seems like the default is already less than infinite, and if anything we should consider making it orders of magnitude smaller?

**Comment by jokeyrhyme** [comment]
Status: [green](https://travis-ci.com/jokeyrhyme/SavedInstances/builds/95872907), `rebase`d on master

**Pull request merged**
